---
title: "Edgeweight as a function of landscape variables"
author: "D. G. Gannon"
date: "July 2021"
output:
  github_document:
    pandoc_args: --webtex
bibliography: /Users/dusty/Documents/zotero_library.bib
---

```{r setup, message=FALSE}

require(rstan)
require(tidyverse)
require(here)

```


## Load model fit

```{r}

  mfit <- readRDS(here(
    "Data",
    "mfit_full_dist_interactions_wm_wc_re.rds"
  ))

# extract beta posteriors
  beta_post <- as.data.frame(rstan::extract(mfit, pars="beta"))
  beta_post_mat <- as.matrix(beta_post)

```
## Predict and plot

### Canopy cover - distance relationship

#### Create matrix $\tilde {\bf X}$ for prediction

```{r}

# create df for canopy preds
  canopy_df <- tibble(
    dist = rep(seq(0,2, length.out = 200), 2),
    dens = rep(5, 400),
    cover= c(rep(0, 200), rep(1, 200)),
    iso = rep(0,400),
    dist_by_dens = dist*dens,
    dist_by_cov = dist*cover,
    dist_by_iso = dist*iso,
    same_comp = rep(0,400),
    same_mead = rep(0,400),
    type = c(rep("open",200), rep("closed",200))
  )

# create model matrix
  X_canopy <- cbind(
    rep(1,400),
    as.matrix(canopy_df[,1:9])
  )
```

#### Plot
 
```{r}
# predict
  post_preds_can <- X_canopy%*%t(beta_post_mat)

# add predictive means and quantiles to canopy_df
  canopy_df <- canopy_df %>%
    mutate(
      pred = apply(post_preds_can, 1, mean),
      low = apply(post_preds_can, 1, quantile, probs=0.025),
      high = apply(post_preds_can, 1, quantile, probs=0.975)
    )
  
# plot predictions

## Plot theme
  pred_theme <- theme(
    panel.background = element_blank(),
    axis.line = element_line(colour = "black"),
    axis.text = element_text(
      family = "Times New Roman",
      colour = "black",
      size = 12
    ),
    axis.title = element_text(
      family = "Times New Roman",
      size = 14
    ),
    legend.text = element_text(
      family = "Times New Roman",
      size = 12
    ),
    plot.title = element_text(
      family = "Times New Roman",
      face = "bold",
      size=18
    )
  )
  
## Plot
  canopy_plot <- ggplot(data = canopy_df, aes(x=dist, y=pred, group=type))+
    geom_ribbon(
      aes(ymin=low, ymax=high, fill=type, color=type),
      alpha=0.3,
      linetype="dashed",
      size=0.2,
      show.legend = FALSE
    ) +
    geom_line(aes(color=type), size=1.3)+
    pred_theme+
    scale_color_manual(
      values = c("#50514F", "#FFE066"),
      labels = c("Closed canopy", "Open canopy") 
    )+
    scale_fill_manual(
      values = c("#50514F", "#FFE066")
    )+
    ylab("log(Edge Weight)\n")+
    xlab("")+
    labs(color="")+
    ggtitle("b)")


```

### Isolation-distance relationship

#### Create matrix $\tilde {\bf X}$ for prediction

```{r}

# create df for canopy preds
  iso_df <- tibble(
    dist = rep(seq(0,2, length.out = 200), 2),
    dens = rep(5, 400),
    cover= rep(0, 400),
    iso = c(rep(0,200), rep(1,200)),
    dist_by_dens = dist*dens,
    dist_by_cov = dist*cover,
    dist_by_iso = dist*iso,
    same_comp = rep(0,400),
    same_mead = rep(0,400),
    type = c(rep("Connected",200), rep("Isolated",200))
  )

# create model matrix
  X_iso <- cbind(
    rep(1,400),
    as.matrix(iso_df[,1:9])
  )

```


#### Plot

```{r}

# predict
  post_preds_iso <- X_iso%*%t(beta_post_mat)

# add predictive means and quantiles to canopy_df
  iso_df <- iso_df %>%
    mutate(
      pred = apply(post_preds_iso, 1, mean),
      low = apply(post_preds_iso, 1, quantile, probs=0.025),
      high = apply(post_preds_iso, 1, quantile, probs=0.975)
    )
  
# plot predictions

## Plot
  iso_plot <- ggplot(data = iso_df, aes(x=dist, y=pred, group=type))+
    geom_ribbon(
      aes(ymin=low, ymax=high, fill=type, color=type),
      alpha=0.2,
      linetype="dashed",
      size=0.2,
      show.legend = FALSE
    ) +
    geom_line(aes(color=type), size=1.3)+
    pred_theme+
    scale_color_manual(
      values = c("#70C1B3", "#50514F"),
      labels = c("Connected", "Isolated")
    )+
    scale_fill_manual(
      values = c("#70C1B3", "#50514F")
    )+
    ylab("log(Edge Weight)\n")+
    xlab("\nGeographic distance (km)")+
    labs(color="")+
    ggtitle("d)")
  
# arrange both plots and save image
  png(
    filename = here(
      "Figures",
      "interaction_plots.png"
    ),
    width = 1500,
    height = 1800,
    res = 300
  )
    gridExtra::grid.arrange(
      canopy_plot,
      iso_plot,
      nrow=2
    )
  dev.off()

```








