---
title: "Columbine focals - seed sets"
author: "D. G. Gannon"
date: "7/7/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

  library(dplyr)
  library(stringr)
  library(lme4)
  library(merTools)
  library(ggplot2)

```


```{r}

  seeds <- read.csv("~/Documents/Columbine/Data/AQUFOR_focals/AQUFOR_seed_counts_16_17.csv", header = T, as.is = T)

  plant_data <- read.csv("~/Documents/Columbine/Data/AQUFOR_focals/AQUFOR_focal_data.csv", header = T, as.is = T)

```

Create better plant identifier:

```{r}

  seeds$Plant <- paste(seeds$Meadow, str_remove(seeds$Plant, "AQUFOR"), sep="")
  plant_data$Plant <- paste(plant_data$Meadow, str_remove(plant_data$Plant, "AQUFOR"), sep = "")
  
  plnt_trt <- plant_data[,which(names(plant_data) %in% 
                                  c("Plant", "Treatment", "flrs_5m_radius"))]
  
# Plants without a defined treatments were not manipulated
  plnt_trt$Treatment[is.na(plnt_trt$Treatment)] <- "UNCAGED"
  
# merge the two datasets
  seeds2 <- merge(seeds, plnt_trt, by="Plant")
  
# total the seed count for a given plant
  seed_cols <- str_which(names(seeds2), pattern = "seeds")
  for(j in 1:length(seed_cols)){
    seeds2[which(is.na(seeds2[,seed_cols[j]])), seed_cols[j]] <- 0
  }
  
  seeds2$seedsTotal <- apply(seeds2[,seed_cols], 1, sum)
  
# now impute missing plant density values from independent data
  gbs_plants <- read.csv("~/Documents/Columbine/Data/sample_data_allplants.csv", header=T)
  
  mdws_2impute <- unique(seeds2$Meadow[which(is.na(seeds2$flrs_5m_radius))])
  
  flrs5m_gbs <- subset(gbs_plants[,c(2,12)], MEADOW_ID %in% mdws_2impute)
  
  meanflrs_5m <- group_by(flrs5m_gbs, MEADOW_ID) %>% summarise(., estim=mean(PL_IN_5M))
  
  for(i in 1:nrow(seeds2)){
    if(is.na(seeds2$flrs_5m_radius[i])){
      seeds2$flrs_5m_radius[i] <- meanflrs_5m$estim[which(meanflrs_5m$MEADOW_ID == seeds2$Meadow[i])]
    }
  }
  
```

 Condense the dataset into the important components:

```{r}
# now sum the total number of seeds and pods within a given 
  # treatment*meadow*year
  cols2keep <- c("Plant", "Date", "Meadow", "pods", "seedsTotal", "Treatment", "flrs_5m_radius")
  
  seeds3 <- seeds2[,which(names(seeds2) %in% cols2keep)]
  
# check for duplicated rows
  dups <- which(duplicated(seeds3[,1:3]))
  
# combine seeds and pods, then remove duplicates
  for(i in 1:length(dups)){
    seeds3$pods[dups[i]-1] <- seeds3$pods[dups[i]-1] + seeds3$pods[dups[i]]
    seeds3$seedsTotal[dups[i]-1] <- seeds3$seedsTotal[dups[i]-1] + seeds3$seedsTotal[dups[i]]
  }
  seeds3 <- seeds3[-dups, ]

```


Now bring in measurements on meadow size and connectivity:



```{r}

  mdw_data <-  read.csv("~/Documents/Columbine/Data/meadow_data.csv")

  seeds4 <- merge(seeds3, mdw_data, by.x = "Meadow", by.y = "MEADOW_ID")

```


```{r modeling}

  seeds4$seeds_per_pod <- seeds4$seedsTotal/seeds4$pods

  seeds4$log.size <- log(seeds4$MEADOW_AREA, base = 10)
  
# factorize treatment and year
  seeds4$f.trt <- factor(seeds4$Treatment, levels = c("UNCAGED", "CAGED"))
  seeds4$f.year <- factor(seeds4$Date)
  seeds4$f.meadow <- factor(seeds4$Meadow)
  
# assess importance of nuisance variable "year"
  nuis_m1 <- lmer(seeds_per_pod~f.year + (1|f.meadow), data = seeds4)
  
# year looks to explain a decent amount of variation
  
# full model
  m1 <- lmer(seeds_per_pod~f.year + flrs_5m_radius + log.size + f.trt + log.size*f.trt +
               (1|f.meadow), data = seeds4)
  
```

Model fit and residuals look good to me. Create new data for predicting over a range of meadow sizes.


```{r predictions}

  newdat <- data.frame(f.year = rep("2017",40),
                       flrs_5m_radius=rep(mean(seeds4$flrs_5m_radius),40),
                       log.size=rep(seq(2,5,length.out = 20),2),
                       f.trt = rep(unique(seeds4$f.trt), each=20),
                       f.meadow = rep("M1M3", 40))
  newdat$f.meadow <- factor(newdat$f.meadow, levels=levels(seeds4$f.meadow))
  newdat$f.trt <- factor(newdat$f.trt, levels = levels(seeds4$f.trt))
  newdat$f.year <- factor(newdat$f.year, levels = levels(seeds4$f.year))
  
  predfun <- function(fit){
    predict(fit, newdat)
  }
  
 # bootstrap prediction intervals 
  boots <- bootMer(m1, FUN = predfun, nsim = 1000, use.u = F)
  
# plot results
  df.plot <- data.frame(Treatment=newdat$f.trt,
                        log.size=newdat$log.size,
                        estim=predfun(m1),
                        low=apply(boots[["t"]], 2, quantile, probs=0.025),
                        high=apply(boots[["t"]], 2, quantile, probs=0.975))
  
  cage.seeds <- subset(seeds4, Treatment=="CAGED")
  open.seeds <- subset(seeds4, Treatment=="UNCAGED")
  open.col <- rgb(112,193,179, maxColorValue = 255)
  cage.col <- rgb(80,81,79, maxColorValue = 255)
  
png(filename = "~/Documents/Columbine/Analysis/Columbine_analysis/Seed_sets/seeds_figure.png",
    width = 1800, height = 1200, res=300)
  ggplot()+
    geom_point(data = seeds4, aes(x=log.size, y=seeds_per_pod, color=f.trt), size=1)+
    geom_line(data = df.plot[1:20,], aes(x=log.size, y=estim), color=open.col, size=1.2)+
    geom_ribbon(data = df.plot[1:20,], aes(ymin=low, ymax=high, x=log.size), fill=open.col, alpha=0.1)+
    #geom_point(data = cage.seeds, aes(x=log.size, y=seeds_per_pod), color=cage.col, shape=1, size=2)+
    geom_line(data=df.plot[21:40,], aes(x=log.size, y=estim), color=cage.col, size=1.2, linetype="dashed")+
    geom_ribbon(data=df.plot[21:40,], aes(ymin=low, ymax=high, x=log.size), fill=cage.col, alpha=0.1)+
    theme_bw()+
    theme(axis.text = element_text(size=12, family = "Arial"),
          axis.title = element_text(family = "Arial", size=14),
          legend.text = element_text(size=12))+
    xlab("log(Meadow size)")+
    ylab("Seeds per seed pod")+
    scale_color_manual(name="Treatment", values = c(open.col, cage.col), labels=c("Open","Bird exclusion"))
dev.off()

```











